### ISSUE TITLE
Library needs recompile against latest version of Compose

### ISSUE THREAD

**Issue by spacecowboy** [Kodein-Framework/Kodein-DI-Compose#1]
Error:

```
Process: com.nononsenseapps.feeder.debug, PID: 12278
    java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer; in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/~~KToeY0tG7VCUZsOkmxArBQ==/com.nononsenseapps.feeder.debug-rt4YMeIzgGlveXHHvJ2pcg==/base.apk)
        at org.kodein.di.compose.AndroidContextKt.withDI(androidContext.kt:29)
```

This is explained at https://developer.android.com/jetpack/androidx/releases/compose-ui#1.0.0-beta07

> Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)
